const POPULATEDATA = "POPULATEDATA";
const FETCHING_BOOKS = 'FETCHING_BOOKS'
const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS'
const FETCH_BOOKS_ERROR = 'FETCH_BOOKS_ERROR'
const FETCH_DETAILS_SUCCESS = 'FETCH_DETAILS_SUCCESS'
const FETCHING_BOOK_DETAILS = 'FETCHING_BOOK_DETAILS'
const HIDE_SUGGESTION = 'HIDE_SUGGESTION'
const EMPTY_QUERY = 'EMPTY_QUERY'

const API_KEY = "Rc0dvbXtAxvyAG9V7UA"
export default {
    POPULATEDATA,

    FETCHING_BOOKS,
    FETCH_BOOKS_SUCCESS,
    FETCH_BOOKS_ERROR,
    FETCH_DETAILS_SUCCESS,
    FETCHING_BOOK_DETAILS,
    HIDE_SUGGESTION,
    EMPTY_QUERY,

    API_KEY
}